# Generated by Django 4.2.7 on 2025-11-02 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Type')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('module', models.CharField(choices=[('authentication', 'Authentification'), ('clients', 'Clients'), ('products', 'Produits'), ('orders', 'Commandes'), ('deliveries', 'Livraisons'), ('reports', 'Rapports'), ('stock', 'Stock'), ('system', 'Système')], max_length=50, verbose_name='Module')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('endpoint', models.CharField(blank=True, max_length=255, verbose_name='Endpoint')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Code de statut')),
                ('response_time', models.CharField(blank=True, max_length=50, verbose_name='Temps de réponse')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log Système',
                'verbose_name_plural': 'Logs Système',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='logs_system_timesta_d0a88c_idx'), models.Index(fields=['type'], name='logs_system_type_541a40_idx'), models.Index(fields=['module'], name='logs_system_module_a2753a_idx'), models.Index(fields=['user'], name='logs_system_user_id_944528_idx')],
            },
        ),
    ]
