# Generated by Django 4.2.7 on 2025-10-22 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_update_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_livraison', models.CharField(max_length=50, unique=True, verbose_name='Numéro de livraison')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('retournee', 'Retournée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_livraison_prevue', models.DateTimeField(verbose_name='Date de livraison prévue')),
                ('heure_depart', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('instructions_livraison', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('vehicule', models.CharField(blank=True, max_length=100, verbose_name='Véhicule utilisé')),
                ('signature_client', models.TextField(blank=True, verbose_name='Signature du client')),
                ('nom_receptionnaire', models.CharField(blank=True, max_length=200, verbose_name='Nom du réceptionnaire')),
                ('notes_livreur', models.TextField(blank=True, verbose_name='Notes du livreur')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distance (km)')),
                ('cout_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût de livraison (HTG)')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='orders.commande', verbose_name='Commande')),
                ('livreur', models.ForeignKey(blank=True, limit_choices_to={'role': 'livreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to=settings.AUTH_USER_MODEL, verbose_name='Livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
    ]
