# Generated by Django 4.2.7 on 2025-11-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livraison',
        ),
    ]
