# Generated by Django 4.2.7 on 2025-10-08 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('validee', 'Validée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='attente', max_length=20, verbose_name='Statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_livraison_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
                ('adresse_livraison', models.TextField(blank=True, help_text="Si différente de l'adresse du client", verbose_name='Adresse de livraison')),
                ('instructions_livraison', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client', verbose_name='Client')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_vendeur', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ItemCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'unique_together': {('commande', 'produit')},
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero_commande'], name='orders_comm_numero__364ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', '-date_creation'], name='orders_comm_client__3fd014_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='orders_comm_statut_68f2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['vendeur'], name='orders_comm_vendeur_7ef581_idx'),
        ),
    ]
