# Generated by Django 4.2.7 on 2025-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total en Gourdes Haïtiennes', max_digits=12, verbose_name='Montant total (HTG)'),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire en Gourdes Haïtiennes', max_digits=10, verbose_name='Prix unitaire (HTG)'),
        ),
        migrations.AlterField(
            model_name='itemcommande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, help_text='Sous-total en Gourdes Haïtiennes', max_digits=12, verbose_name='Sous-total (HTG)'),
        ),
    ]
