# Generated by Django 4.2.7 on 2025-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_commande_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_commande',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de commande'),
        ),
    ]
