# Generated by Django 4.2.7 on 2025-10-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_commande_numero_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, help_text='15% du montant pour livraison à domicile, 0 pour retrait en magasin', max_digits=12, verbose_name='Frais de livraison (HTG)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_produits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total des produits uniquement', max_digits=12, verbose_name='Montant des produits (HTG)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_livraison',
            field=models.CharField(choices=[('retrait_magasin', 'Retrait en magasin'), ('livraison_domicile', 'Livraison à domicile')], default='retrait_magasin', max_length=20, verbose_name='Type de livraison'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total = montant produits + frais de livraison', max_digits=12, verbose_name='Montant total (HTG)'),
        ),
    ]
