# Generated by Django 4.2.7 on 2025-10-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_update_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.CharField(blank=True, help_text='Nom du livreur assigné à cette commande', max_length=100, null=True, verbose_name='Livreur'),
        ),
    ]
