# Generated by Django 4.2.7 on 2025-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commande_frais_livraison_commande_montant_produits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('confirmee', 'Confirmée'), ('validee', 'Validée'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='attente', max_length=20, verbose_name='Statut'),
        ),
    ]
