# Generated by Django 4.2.7 on 2025-11-14 21:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_alter_vente_methode_paiement'),
        ('orders', '0004_commande_livreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='convertie_en_vente',
            field=models.BooleanField(default=False, verbose_name='Convertie en vente'),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant payé (HTG)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_restant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant restant (HTG)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('impaye', 'Impayé'), ('paye_partiel', 'Payé Partiellement'), ('paye', 'Payé')], default='impaye', max_length=20, verbose_name='Statut de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente_associee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_origine', to='sales.vente', verbose_name='Vente associée'),
        ),
        migrations.CreateModel(
            name='PaiementCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (HTG)')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Paiement mobile')], max_length=20, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_commande', to='orders.commande', verbose_name='Commande')),
                ('recu_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Paiement de commande',
                'verbose_name_plural': 'Paiements de commande',
                'db_table': 'paiements_commande',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
