# Generated by Django 4.2.7 on 2025-10-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('annulee', 'Annulée'), ('validee', 'Validée'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
