# Generated by Django 4.2.7 on 2025-11-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_commande_convertie_en_vente_commande_montant_paye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_echeance',
            field=models.DateField(blank=True, help_text='Date limite pour le paiement du montant restant', null=True, verbose_name="Date d'échéance"),
        ),
    ]
