# Generated by Django 4.2.7 on 2025-12-04 22:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_commande_date_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_penalite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pénalité de 1.5% sur le montant restant si paiement après échéance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant pénalité (HTG)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_echeance',
            field=models.DateField(blank=True, help_text='Date limite pour le paiement du montant restant (1 jour avant livraison)', null=True, verbose_name="Date d'échéance"),
        ),
    ]
