# Generated by Django 4.2.7 on 2025-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendeur', 'Vendeur'), ('stock', 'Stock'), ('livreur', 'Livreur')], max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('start_hour', models.IntegerField(default=7)),
                ('start_minute', models.IntegerField(default=0)),
                ('end_hour', models.IntegerField(default=18)),
                ('end_minute', models.IntegerField(default=0)),
                ('allowed_days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_hours_config',
            },
        ),
    ]
