# Generated by Django 4.2.7 on 2025-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_businesshoursconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshoursconfig',
            options={'verbose_name': 'Configuration horaire', 'verbose_name_plural': 'Configurations horaires'},
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='allowed_days',
            field=models.JSONField(default=list, verbose_name='Jours autorisés'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Restriction activée'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='end_hour',
            field=models.IntegerField(default=18, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='end_minute',
            field=models.IntegerField(default=0, verbose_name='Minute de fin'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='role',
            field=models.CharField(choices=[('vendeur', 'Vendeur'), ('stock', 'Stock'), ('livreur', 'Livreur')], max_length=20, unique=True, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='start_hour',
            field=models.IntegerField(default=7, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='businesshoursconfig',
            name='start_minute',
            field=models.IntegerField(default=0, verbose_name='Minute de début'),
        ),
    ]
