# Generated by Django 4.2.7 on 2025-11-06 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_businesshoursconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_timeout', models.IntegerField(default=30, help_text="Durée d'inactivité avant déconnexion automatique (5-480 minutes)", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Nombre maximum de tentatives de connexion avant blocage (3-10)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('lockout_duration', models.IntegerField(default=15, help_text='Durée de blocage après échec de connexion (5-60 minutes)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('password_min_length', models.IntegerField(default=8, help_text='Longueur minimale du mot de passe (6-20 caractères)', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)])),
                ('require_uppercase', models.BooleanField(default=True, help_text='Exiger au moins une majuscule')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Exiger au moins une minuscule')),
                ('require_numbers', models.BooleanField(default=True, help_text='Exiger au moins un chiffre')),
                ('require_special_chars', models.BooleanField(default=False, help_text='Exiger au moins un caractère spécial')),
                ('jwt_access_token_lifetime', models.IntegerField(default=60, help_text="Durée de validité du token d'accès (5-1440 minutes)", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('jwt_refresh_token_lifetime', models.IntegerField(default=1440, help_text='Durée de validité du token de rafraîchissement (60-10080 minutes / 7 jours)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(10080)])),
                ('enable_two_factor', models.BooleanField(default=False, help_text="Activer l'authentification à deux facteurs (futur)")),
                ('force_password_change', models.IntegerField(default=0, help_text='Forcer changement de mot de passe tous les X jours (0 = désactivé)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres de sécurité',
                'verbose_name_plural': 'Paramètres de sécurité',
                'db_table': 'security_settings',
            },
        ),
    ]
