# Generated by Django 4.2.7 on 2025-11-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_securitysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_client_created', models.BooleanField(default=True, verbose_name='Nouveau client créé')),
                ('notify_order_created', models.BooleanField(default=True, verbose_name='Nouvelle commande créée')),
                ('notify_order_validated', models.BooleanField(default=True, verbose_name='Commande validée')),
                ('notify_delivery_assigned', models.BooleanField(default=True, verbose_name='Livraison assignée')),
                ('notify_delivery_completed', models.BooleanField(default=True, verbose_name='Livraison terminée')),
                ('notify_stock_low', models.BooleanField(default=True, verbose_name='Stock faible')),
                ('notify_stock_updated', models.BooleanField(default=False, verbose_name='Stock mis à jour')),
                ('notify_system_errors', models.BooleanField(default=True, verbose_name='Erreurs système')),
                ('notify_security_alerts', models.BooleanField(default=True, verbose_name='Alertes de sécurité')),
                ('notify_daily_report', models.BooleanField(default=False, verbose_name='Rapport quotidien')),
                ('notify_weekly_report', models.BooleanField(default=False, verbose_name='Rapport hebdomadaire')),
                ('notify_monthly_report', models.BooleanField(default=False, verbose_name='Rapport mensuel')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('enable_browser_notifications', models.BooleanField(default=True, verbose_name='Notifications navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notification_preferences',
            },
        ),
    ]
