# Generated by Django 4.2.7 on 2025-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_notificationpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
    ]
