# Generated by Django 4.2.7 on 2025-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Client'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_sale_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Vente'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Nouvelle commande'), ('order_validated', 'Commande validée'), ('order_in_preparation', 'Commande en préparation'), ('order_in_delivery', 'Commande en livraison'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('order_updated', 'Commande modifiée'), ('payment_received', 'Paiement reçu'), ('payment_partial', 'Paiement partiel'), ('stock_low', 'Stock faible'), ('stock_out', 'Rupture de stock'), ('product_created', 'Nouveau produit'), ('product_updated', 'Produit modifié'), ('stock_movement', 'Mouvement de stock'), ('client_created', 'Nouveau client'), ('client_updated', 'Client modifié'), ('sale_created', 'Nouvelle vente'), ('sale_completed', 'Vente finalisée'), ('delivery_assigned', 'Livraison assignée'), ('delivery_completed', 'Livraison terminée')], max_length=50, verbose_name='Type'),
        ),
    ]
