# Generated by Django 4.2.7 on 2025-11-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_notification_related_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text="Date et heure de la dernière activité de l'utilisateur", null=True, verbose_name='Dernière activité'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token JWT')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='Information appareil')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de connexion')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de déconnexion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'db_table': 'user_sessions',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'), models.Index(fields=['token'], name='user_sessio_token_7a1a38_idx')],
            },
        ),
    ]
