# Generated by Django 4.2.7 on 2025-10-08 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(help_text="Nom sous lequel l'entreprise est connue", max_length=200, verbose_name='Nom commercial')),
                ('raison_sociale', models.CharField(help_text="Dénomination officielle de l'entreprise", max_length=200, verbose_name='Raison sociale')),
                ('telephone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('contact', models.CharField(help_text='Nom de la personne à contacter', max_length=200, verbose_name='Personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('credit_limite', models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum autorisé à crédit', max_digits=12, verbose_name='Limite de crédit')),
                ('credit_utilise', models.DecimalField(decimal_places=2, default=0, help_text='Montant actuellement dû', max_digits=12, verbose_name='Crédit utilisé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, help_text='Remarques particulières sur le client', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_commercial'],
                'indexes': [models.Index(fields=['nom_commercial'], name='clients_cli_nom_com_1def05_idx'), models.Index(fields=['telephone'], name='clients_cli_telepho_8c69d9_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx')],
            },
        ),
    ]
