# Generated by Django 4.2.7 on 2025-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_limite',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum autorisé à crédit en Gourdes Haïtiennes', max_digits=12, verbose_name='Limite de crédit (HTG)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_utilise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant actuellement dû en Gourdes Haïtiennes', max_digits=12, verbose_name='Crédit utilisé (HTG)'),
        ),
    ]
