# Generated by Django 4.2.7 on 2025-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_credit_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom_commercial',
            field=models.CharField(blank=True, help_text="Nom sous lequel l'entreprise est connue", max_length=200, null=True, verbose_name='Nom commercial'),
        ),
    ]
