# Generated by Django 4.2.7 on 2025-10-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_nom_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, help_text="Dénomination officielle de l'entreprise", max_length=200, null=True, verbose_name='Raison sociale'),
        ),
    ]
