# Generated by Django 4.2.7 on 2025-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_raison_sociale'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('entreprise', 'Entreprise'), ('particulier', 'Particulier')], default='entreprise', help_text='Indique si le client est une entreprise ou un particulier', max_length=20, verbose_name='Type de client'),
        ),
    ]
