# Generated by Django 4.2.7 on 2025-10-08 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_produit', models.CharField(choices=[('eau', 'Eau potable'), ('glace', 'Glace')], max_length=20, verbose_name='Type de produit')),
                ('unite_mesure', models.CharField(choices=[('litre', 'Litre'), ('sachet', 'Sachet'), ('bidon', 'Bidon'), ('bouteille', 'Bouteille'), ('kg', 'Kilogramme'), ('bloc', 'Bloc')], max_length=20, verbose_name='Unité de mesure')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('stock_actuel', models.PositiveIntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_minimal', models.PositiveIntegerField(default=10, help_text="Seuil d'alerte pour le stock faible", verbose_name='Stock minimal')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='products_pr_nom_782f68_idx'), models.Index(fields=['type_produit'], name='products_pr_type_pr_6e82a9_idx'), models.Index(fields=['is_active'], name='products_pr_is_acti_2e7144_idx')],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement'), ('perte', 'Perte')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('stock_avant', models.PositiveIntegerField(help_text='Stock avant le mouvement', verbose_name='Stock avant')),
                ('stock_apres', models.PositiveIntegerField(help_text='Stock après le mouvement', verbose_name='Stock après')),
                ('motif', models.CharField(help_text='Raison du mouvement', max_length=200, verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('numero_document', models.CharField(blank=True, help_text='Référence du bon, facture, etc.', max_length=100, verbose_name='Numéro de document')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='products.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['produit', '-date_creation'], name='products_mo_produit_c6b385_idx'), models.Index(fields=['type_mouvement'], name='products_mo_type_mo_9ef72d_idx'), models.Index(fields=['date_creation'], name='products_mo_date_cr_10c6e5_idx')],
            },
        ),
    ]
