# Generated by Django 4.2.7 on 2025-10-08 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix en Gourdes Haïtiennes (HTG)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (HTG)'),
        ),
    ]
