# Generated by Django 4.2.7 on 2025-10-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produit_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(help_text='Type de produit (eau, glace, ou type personnalisé)', max_length=50, verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_mesure',
            field=models.CharField(help_text='Unité de mesure (litre, kg, unité, ou unité personnalisée)', max_length=50, verbose_name='Unité de mesure'),
        ),
    ]
