# Generated by Django 4.2.7 on 2025-10-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produit_type_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, help_text='Code unique généré automatiquement', max_length=20, null=True, unique=True, verbose_name='Code produit'),
        ),
    ]
