# Generated by Django 4.2.7 on 2025-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_make_code_produit_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(help_text='Code unique généré automatiquement', max_length=20, unique=True, verbose_name='Code produit'),
        ),
    ]
