# Generated by Django 4.2.7 on 2025-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_produit_code_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0, help_text='Stock de référence pour calculer le pourcentage', verbose_name='Stock initial'),
        ),
    ]
