# Generated by Django 4.2.7 on 2025-11-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Paiement mobile'), ('credit', 'Crédit'), ('mixte', 'Paiement mixte')], max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
