# Generated by Django 4.2.7 on 2025-11-19 18:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_vente_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='frais_supplementaires',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais supplémentaires (HTG)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='raison_frais',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raison des frais supplémentaires'),
        ),
    ]
