# Generated by Django 4.2.7 on 2025-11-24 18:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_vente_frais_supplementaires_vente_raison_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue'),
        ),
        migrations.AddField(
            model_name='vente',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de livraison (HTG)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='type_livraison',
            field=models.CharField(choices=[('retrait_magasin', 'Retrait en magasin'), ('livraison_domicile', 'Livraison à domicile')], default='retrait_magasin', max_length=50, verbose_name='Type de livraison'),
        ),
    ]
